(in-package :ruby-parser)

(defparameter standard-optimize-settings
  '(optimize (speed 3) (safety 1) (space 0)))

(defparameter *terminals*
  '(:kCLASS :kMODULE :kDEF :kUNDEF :kBEGIN :kRESCUE :kENSURE :kEND :kIF :kUNLESS
    :kTHEN :kELSIF :kELSE :kCASE :kWHEN :kWHILE :kUNTIL :kFOR :kBREAK :kNEXT
    :kREDO :kRETRY :kIN :kDO :kDO-COND :kDO-BLOCK :kRETURN :kYIELD :kSUPER
    :kSELF :kNIL :kTRUE :kFALSE :kAND :kOR :kNOT :kIF-MOD :kUNLESS-MOD :kWHILE-MOD
    :kUNTIL-MOD :kRESCUE-MOD :kALIAS :kDEFINED :klBEGIN :klEND :k__LINE__
    :k__FILE__ :tIDENTIFIER :tFID :tGVAR :tIVAR :tCONSTANT :tCVAR :tNTH-REF
    :tBACK-REF :tSTRING-CONTENT :tINTEGER :tFLOAT :tREGEXP-END :tUPLUS
    :tUMINUS :tUMINUS-NUM :tPOW :tCMP :tEQ :tEQL :tEQQ :tNEQ :tGEQ :tLEQ :tANDOP
    :tOROP :tMATCH :tNMATCH :tDOT :tDOT2 :tDOT3 :tAREF :tASET :tLSHFT :tRSHFT
    :tCOLON2 :tCOLON3 :tOP-ASGN :tASSOC :tLPAREN :tLPAREN2 :tRPAREN :tLPAREN-ARG
    :tLBRACK |[| :tRBRACK :tLBRACE :tLBRACE-ARG :tSTAR :tSTAR2 :tAMPER :tAMPER2
    :tTILDE :tPERCENT :tDIVIDE :tPLUS :tMINUS :tLT :tGT :tPIPE :tBANG :tCARET
    :tLCURLY :tRCURLY :tBACK-REF2 :tSYMBEG :tSTRING-BEG :tXSTRING-BEG :tREGEXP-BEG
    :tWORDS-BEG :tAWORDS-BEG :tSTRING-DBEG :tSTRING-DVAR :tSTRING-END :tSTRING
    :tSYMBOL :tNL :tEH :tCOLON :tCOMMA :tSPACE :tSEMI))

